### ISSUE TITLE
Bug: Changes made to PersonCard don't update on PersonPanel

### ISSUE THREAD

**Issue by amad-person** [CS2103JAN2018-W13-B1/main#204]
`groupdelete friends`:

<img width="1280" alt="screen shot 2018-04-11 at 4 24 38 pm" src="https://user-images.githubusercontent.com/22164211/38605230-474b2e2c-3da5-11e8-8f02-644a14c804b9.png">

The deletion doesn't update in PersonPanel:

<img width="1280" alt="screen shot 2018-04-11 at 4 24 47 pm" src="https://user-images.githubusercontent.com/22164211/38605232-49a8f01e-3da5-11e8-98a8-06e3594d4e9b.png">

**Comment by AJZ1995** [comment]
Resolved

**Comment by amad-person** [comment]
This is still happening after the bug fix, any ideas on how to resolve this bug?

**Comment by AJZ1995** [comment]
I realized that there is a need to 're-select' the person card at the person list panel to reflect the changes.

**Comment by amad-person** [comment]
UserGuide has been updated.
